from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor
from logging import getLogger
from typing import TYPE_CHECKING, Callable

from src.genai.providers import Provider

if TYPE_CHECKING:
    from src.mcp.manager import MCPManager

logger = getLogger(__name__)

MAX_TOOL_ROUNDS = 5


class AIModelFacade:
    """Facade around provider-specific AI clients for chat interactions."""

    def __init__(
        self,
        provider: Provider,
        model: str,
        system_prompt: str,
        history: list[dict[str, str]]
    ):
        """
        Initializes the AIModelFacade with the specified model and sets up
        the AI client.

        Parameters
        ----------
        provider : Provider
            The provider of the AI model to use for generating responses.
        model : str
            The name of the AI model to use for generating responses.
        system_prompt : str
            The system prompt that defines context and behavior instructions.
        history : list[dict[str, str]]
            Existing conversation history to prepend after the system message.

        Returns
        -------
        None
            Initializes internal client and conversation history state.
        """

        self.model = model
        self.provider = provider
        self.system_prompt = system_prompt
        self.history = [
            {"role": "system", "content": self.system_prompt},
            *history
        ]

        if provider == Provider.OLLAMA:
            from src.genai.clients.ollama import get_ollama_client
            self.client = get_ollama_client()
        elif provider == Provider.GEMINI:
            from src.genai.clients.gemini import get_gemini_client
            self.client = get_gemini_client()
        elif provider == Provider.OPEN_ROUTER:
            from src.genai.clients.openrouter import get_openrouter_client
            self.client = get_openrouter_client()
        else:
            raise ValueError(f"Unsupported provider: {provider}")


    def add_to_history(self, role: str, content: str) -> None:
        """
        Adds a message to the conversation history.

        Parameters
        ----------
        role : str
            Chat role of message (for example, ``user`` or ``assistant``).
        content : str
            Message content to append.

        Returns
        -------
        None
            The message is appended to in-memory history.
        """

        self.history.append({"role": role, "content": content})

    def generate_response(
        self,
        user_message: str,
        retrieval_context: str | None = None,
        mcp_manager: MCPManager | None = None,
        on_tool_call: Callable[[str, dict], bool] | None = None,
        skill_instructions: str | None = None,
    ) -> str:
        """
        Generates a response to the user's message using the AI model
        and the system prompt.

        Parameters
        ----------
        user_message : str
            The message from the user to which the agent should respond.
        retrieval_context : str | None
            Optional retrieved context injected as a temporary system message.
        mcp_manager : MCPManager | None
            Optional MCP manager providing tool definitions and execution.
        on_tool_call : Callable | None
            Optional callback invoked as ``on_tool_call(tool_name, arguments)``
            each time the model decides to use a tool.

        Returns
        -------
        str
            The response generated by the AI model.
        """

        # Build a local copy of messages for this turn.  Tool-call
        # intermediaries are tracked separately and persisted only when
        # tools were actually used, so the model remembers past tool usage.
        messages: list[dict] = list(self.history)
        tool_messages: list[dict] = []

        if retrieval_context:
            messages.append({"role": "system", "content": f"[context-used]\n{retrieval_context}"})

        if skill_instructions:
            messages.append({"role": "system", "content": f"[skill]\n{skill_instructions}"})

        messages.append({"role": "user", "content": user_message})

        tools = mcp_manager.get_tools() if mcp_manager else None

        try:
            response = None
            tool_cache: dict[tuple[str, str], str] = {}
            for _ in range(MAX_TOOL_ROUNDS):
                response = self.client.chat(
                    model=self.model,
                    messages=messages,
                    tools=tools,
                )

                if not response.has_tool_calls:
                    break

                # Append the assistant's tool-call message
                tool_call_msg = {
                    "role": "assistant",
                    "content": response.content,
                    "tool_calls": [
                        {
                            "id": tc.id,
                            "type": "function",
                            "function": {
                                "name": tc.name,
                                "arguments": json.dumps(tc.arguments),
                            },
                        }
                        for tc in response.tool_calls
                    ],
                }
                messages.append(tool_call_msg)
                tool_messages.append(tool_call_msg)

                # Execute tool calls (sequentially when confirmation needed)
                def _exec_tool(tc: object) -> tuple[object, str]:
                    if on_tool_call:
                        approved = on_tool_call(tc.name, tc.arguments)
                        if not approved:
                            return tc, "Tool call denied by user."
                    cache_key = (tc.name, json.dumps(tc.arguments, sort_keys=True))
                    if cache_key in tool_cache:
                        return tc, tool_cache[cache_key]
                    result = mcp_manager.call_tool(tc.name, tc.arguments)
                    tool_cache[cache_key] = result
                    return tc, result

                if on_tool_call and len(response.tool_calls) > 1:
                    # Run sequentially so confirmation prompts don't overlap
                    results = [_exec_tool(tc) for tc in response.tool_calls]
                else:
                    with ThreadPoolExecutor(max_workers=len(response.tool_calls)) as pool:
                        results = list(pool.map(_exec_tool, response.tool_calls))

                for tc, result in results:
                    tool_result_msg = {
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "name": tc.name,
                        "content": result,
                    }
                    messages.append(tool_result_msg)
                    tool_messages.append(tool_result_msg)

            content = response.content if response else None
            if not content:
                raise ValueError("Received empty response from the AI model.")

        except Exception as e:
            logger.error("AI provider error (%s): %s", self.provider, e)
            content = "Sorry, I'm not feeling very well."

        # Persist user message, any tool interactions, and the final reply
        # so the model remembers it can (and did) use tools.
        self.history.append({"role": "user", "content": user_message})
        self.history.extend(tool_messages)
        self.history.append({"role": "assistant", "content": content})

        return content
