from __future__ import annotations

import json
from logging import getLogger
from typing import TYPE_CHECKING, Callable

from src.genai.providers import Provider

if TYPE_CHECKING:
    from src.mcp.manager import MCPManager

logger = getLogger(__name__)

MAX_TOOL_ROUNDS = 5


class AIModelFacade:
    """Facade around provider-specific AI clients for chat interactions."""

    def __init__(
        self,
        provider: Provider,
        model: str,
        system_prompt: str,
        history: list[dict[str, str]]
    ):
        """
        Initializes the AIModelFacade with the specified model and sets up
        the AI client.

        Parameters
        ----------
        provider : Provider
            The provider of the AI model to use for generating responses.
        model : str
            The name of the AI model to use for generating responses.
        system_prompt : str
            The system prompt that defines context and behavior instructions.
        history : list[dict[str, str]]
            Existing conversation history to prepend after the system message.

        Returns
        -------
        None
            Initializes internal client and conversation history state.
        """

        self.model = model
        self.provider = provider
        self.system_prompt = system_prompt
        self.history = [
            {"role": "system", "content": self.system_prompt},
            *history
        ]

        if provider == Provider.OLLAMA:
            from src.genai.clients.ollama import get_ollama_client
            self.client = get_ollama_client()
        elif provider == Provider.GEMINI:
            from src.genai.clients.gemini import get_gemini_client
            self.client = get_gemini_client()
        elif provider == Provider.OPEN_ROUTER:
            from src.genai.clients.openrouter import get_openrouter_client
            self.client = get_openrouter_client()
        else:
            raise ValueError(f"Unsupported provider: {provider}")


    def add_to_history(self, role: str, content: str) -> None:
        """
        Adds a message to the conversation history.

        Parameters
        ----------
        role : str
            Chat role of message (for example, ``user`` or ``assistant``).
        content : str
            Message content to append.

        Returns
        -------
        None
            The message is appended to in-memory history.
        """

        self.history.append({"role": role, "content": content})

    def generate_response(
        self,
        user_message: str,
        retrieval_context: str | None = None,
        mcp_manager: MCPManager | None = None,
        on_tool_call: Callable[[str, dict], None] | None = None,
        skill_instructions: str | None = None,
    ) -> str:
        """
        Generates a response to the user's message using the AI model
        and the system prompt.

        Parameters
        ----------
        user_message : str
            The message from the user to which the agent should respond.
        retrieval_context : str | None
            Optional retrieved context injected as a temporary system message.
        mcp_manager : MCPManager | None
            Optional MCP manager providing tool definitions and execution.
        on_tool_call : Callable | None
            Optional callback invoked as ``on_tool_call(tool_name, arguments)``
            each time the model decides to use a tool.

        Returns
        -------
        str
            The response generated by the AI model.
        """

        # Build a local copy of messages for this turn so tool-call
        # intermediaries don't pollute the persistent history.
        messages: list[dict] = list(self.history)

        if retrieval_context:
            messages.append({"role": "system", "content": f"[context-used]\n{retrieval_context}"})

        if skill_instructions:
            messages.append({"role": "system", "content": f"[skill]\n{skill_instructions}"})

        messages.append({"role": "user", "content": user_message})

        tools = mcp_manager.get_tools() if mcp_manager else None

        try:
            response = None
            for _ in range(MAX_TOOL_ROUNDS):
                response = self.client.chat(
                    model=self.model,
                    messages=messages,
                    tools=tools,
                )

                if not response.has_tool_calls:
                    break

                # Append the assistant's tool-call message
                messages.append({
                    "role": "assistant",
                    "content": response.content,
                    "tool_calls": [
                        {
                            "id": tc.id,
                            "type": "function",
                            "function": {
                                "name": tc.name,
                                "arguments": json.dumps(tc.arguments),
                            },
                        }
                        for tc in response.tool_calls
                    ],
                })

                # Execute each tool and append results
                for tc in response.tool_calls:
                    if on_tool_call:
                        on_tool_call(tc.name, tc.arguments)

                    result = mcp_manager.call_tool(tc.name, tc.arguments)
                    messages.append({
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "name": tc.name,
                        "content": result,
                    })

            content = response.content if response else None
            if not content:
                raise ValueError("Received empty response from the AI model.")

        except Exception as e:
            logger.error("AI provider error (%s): %s", self.provider, e)
            content = "Sorry, I'm not feeling very well."

        # Only the user message and the final assistant reply are persisted.
        self.history.append({"role": "user", "content": user_message})
        self.history.append({"role": "assistant", "content": content})

        return content
