from __future__ import annotations
from logging import getLogger

from src.ai.providers import Provider

logger = getLogger(__name__)


class AIModelFacade:
    """Facade around provider-specific AI clients for chat interactions."""

    def __init__(
        self, 
        provider: Provider, 
        model: str, 
        system_prompt: str, 
        history: list[dict[str, str]]
    ):
        """
        Initializes the AIModelFacade with the specified model and sets up 
        the AI client.
        
        Parameters
        ----------
        provider : Provider
            The provider of the AI model to use for generating responses.
        model : str
            The name of the AI model to use for generating responses. 
        system_prompt : str
            The system prompt that defines context and behavior instructions.
        history : list[dict[str, str]]
            Existing conversation history to prepend after the system message.

        Returns
        -------
        None
            Initializes internal client and conversation history state.
        """

        self.model = model
        self.provider = provider
        self.system_prompt = system_prompt
        self.history = [
            {"role": "system", "content": self.system_prompt},
            *history
        ]        

        if provider == Provider.OLLAMA:
            from src.ai.clients.ollama import get_ollama_client
            self.client = get_ollama_client()
        elif provider == Provider.GEMINI:
            from src.ai.clients.gemini import get_gemini_client
            self.client = get_gemini_client()
        elif provider == Provider.OPEN_ROUTER:
            from src.ai.clients.openrouter import get_openrouter_client
            self.client = get_openrouter_client()
        else:
            raise ValueError(f"Unsupported provider: {provider}")


    def add_to_history(self, role: str, content: str) -> None:
        """
        Adds a message to the conversation history.

        Parameters
        ----------
        role : str
            Chat role of message (for example, ``user`` or ``assistant``).
        content : str
            Message content to append.

        Returns
        -------
        None
            The message is appended to in-memory history.
        """

        self.history.append({"role": role, "content": content})

    def generate_response(self, user_message: str, retrieval_context: str | None = None) -> str:
        """ 
        Generates a response to the user's message using the AI model 
        and the system prompt.
        
        Parameters
        ----------
        user_message : str
            The message from the user to which the agent should respond.
        retrieval_context : str | None
            Optional retrieved context injected as a temporary system message.

        Returns
        -------
        str
            The response generated by the AI model.
        """
        
        temp_context_added = False
        if retrieval_context:
            self.history.append({"role": "system", "content": f"[context-used]\n{retrieval_context}"})
            temp_context_added = True

        self.history.append({"role": "user", "content": user_message})
 
        try:
            response = self.client.chat(
                model=self.model,
                messages=self.history
            )
            if not response:
                raise ValueError("Received empty response from the AI model.")

        except Exception as e:
            if self.provider == Provider.OLLAMA:
                logger.error(
                    "Ollama error. Start Ollama with `ollama serve`, " \
                    "then run model with `ollama run %s`. Error: %s",
                    self.model,
                    e,
                )
            response = f"Sorry, I'm not feeling very well."

        if temp_context_added:
            user_msg = self.history.pop()
            self.history.pop()
            self.history.append(user_msg)

        self.history.append({"role": "assistant", "content": response})

        return response
