from __future__ import annotations

from src.ai.providers import Provider
import src.constants as c


class AIModelFacade:

    def __init__(
        self, 
        provider: Provider, 
        model: str, 
        system_prompt: str, 
        history: list[dict[str, str]]
    ):
        """
        Initializes the AIModelFacade with the specified model and sets up 
        the AI client.
        
        Parameters
        ----------
        provider: c.Provider
            The provider of the AI model to use for generating responses.
        model: str
            The name of the AI model to use for generating responses. 
        system_prompt: str
            The system prompt to use for the AI model, which defines the context and instructions for generating
        """

        self.model = model
        self.system_prompt = system_prompt
        self.history = [
            {"role": "system", "content": self.system_prompt},
            *history
        ]        

        if provider == Provider.OLLAMA:
            from src.ai.clients.ollama import OllamaClient
            self.client = OllamaClient(host=c.OLLAMA_HOST)
        elif provider == Provider.GEMINI:
            from src.ai.clients.gemini import GeminiClient
            self.client = GeminiClient()
        else:
            raise ValueError(f"Unsupported provider: {provider}")

    def add_to_history(self, role: str, content: str) -> None:
        """Adds a message to the conversation history."""
        self.history.append({"role": role, "content": content})

    def generate_response(self, user_message: str) -> str:
        """ 
        Generates a response to the user's message using the AI model 
        and the system prompt.
        
        Parameters
        ----------
        user_message: str
            The message from the user to which the agent should respond.

        Returns
        -------
        str
            The response generated by the AI model.
        """
        
        self.history.append({"role": "user", "content": user_message})
 
        try:
            response = self.client.chat(
                model=self.model,
                messages=self.history
            )
            if not response:
                raise ValueError("Received empty response from the AI model.")

        except Exception as e:
            response = f"Sorry, I had trouble generating a response. {e}"

        self.history.append({"role": "assistant", "content": response})

        return response
