from src.ai import AIModelFacade
from src.constants import MODEL, MODEL_PROVIDER

class Agent:

    def __init__(self):
        """
        Initializes the agent with the given AI model. 
        If no model is provided, a default model will be used.
        """

        self.history = self._load_recent_conversations()
        self.system_prompt = self._create_system_prompt()
        
        self.ai_model = AIModelFacade(
            provider=MODEL_PROVIDER,
            model=MODEL,
            system_prompt=self.system_prompt,
            history=self.history
        )

    def _create_system_prompt(
        self
    ) -> str:
        """
        Creates a system prompt for the agent based on the given personality.
        """
        
        return f"""
        You are an AI assistant with the following personality:
        {self.personality}
        
        Instructions: 
        - Always respond in a way that is consistent with this personality 
        and help the user with its questions. 
        - Stay in character and do not break the fourth wall. 
        - Every response should reflect the personality traits and 
        characteristics described above. 
        - DO NOT MENTION that you are an AI model or that you are following instructions.
        - DO NOT MENTION that you are a character from the TV show Friends.
        """

    def _load_recent_conversations(self) -> list[dict[str, str]]:
        """
        Loads recent conversations from a file or database. 
        This is a placeholder implementation.
        """
        
        return []

    def start_message(self) -> str:
        """
        Specialized message to say hi. Adds it to conversation history
        so the model knows what it already said.
        """
        self.ai_model.add_to_history("assistant", self.hi_message)
        return self.hi_message

    def message(self, user_message: str) -> str:
        """
        Generates a response to the user's message using the AI model 
        and the system prompt.

        Parameters:
        -----------
        user_message: str
            The message from the user to which the agent should respond.

        Returns:
        --------        
        str
            The response generated by the AI model.
        """
        
        return self.ai_model.generate_response(
            user_message=user_message,
        )